// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkU5EpxZI9uXkINmm1mSjQtb5fj6phCDs',
    appId: '1:713327217412:web:f9560283e24c6be2e09e51',
    messagingSenderId: '713327217412',
    projectId: 'one-bayombong-connect',
    authDomain: 'one-bayombong-connect.firebaseapp.com',
    storageBucket: 'one-bayombong-connect.firebasestorage.app',
    measurementId: 'G-9ZB20835CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3zGAViSaHu9_HPQ2g4Jy1QFtmFuVYPY',
    appId: '1:713327217412:android:ea27f0646d904190e09e51',
    messagingSenderId: '713327217412',
    projectId: 'one-bayombong-connect',
    storageBucket: 'one-bayombong-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuckyuhVMTuhVcfxLY61yyAe7-z4yK7G4',
    appId: '1:713327217412:ios:bf75249ae9397846e09e51',
    messagingSenderId: '713327217412',
    projectId: 'one-bayombong-connect',
    storageBucket: 'one-bayombong-connect.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuckyuhVMTuhVcfxLY61yyAe7-z4yK7G4',
    appId: '1:713327217412:ios:bf75249ae9397846e09e51',
    messagingSenderId: '713327217412',
    projectId: 'one-bayombong-connect',
    storageBucket: 'one-bayombong-connect.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkU5EpxZI9uXkINmm1mSjQtb5fj6phCDs',
    appId: '1:713327217412:web:2ed051f0862aa5d0e09e51',
    messagingSenderId: '713327217412',
    projectId: 'one-bayombong-connect',
    authDomain: 'one-bayombong-connect.firebaseapp.com',
    storageBucket: 'one-bayombong-connect.firebasestorage.app',
    measurementId: 'G-D92W39HEZ2',
  );
}
