// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4a5nFOvYlQzoORTYbdimztyE8ojPk-_Y',
    appId: '1:899155311025:web:39a0ba252222d089dee590',
    messagingSenderId: '899155311025',
    projectId: 'one-vizcaya-app',
    authDomain: 'one-vizcaya-app.firebaseapp.com',
    storageBucket: 'one-vizcaya-app.firebasestorage.app',
    measurementId: 'G-ERSX5CDK5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyHGGWGelU4MGOCdn6yAZi06VtZjVf3oY',
    appId: '1:899155311025:android:2001ac798a04ba93dee590',
    messagingSenderId: '899155311025',
    projectId: 'one-vizcaya-app',
    storageBucket: 'one-vizcaya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArM9SMJuwgxgMKHB-b2J22LjhHUPYlMmU',
    appId: '1:899155311025:ios:cb17cbe02262e24adee590',
    messagingSenderId: '899155311025',
    projectId: 'one-vizcaya-app',
    storageBucket: 'one-vizcaya-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArM9SMJuwgxgMKHB-b2J22LjhHUPYlMmU',
    appId: '1:899155311025:ios:cb17cbe02262e24adee590',
    messagingSenderId: '899155311025',
    projectId: 'one-vizcaya-app',
    storageBucket: 'one-vizcaya-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHOn7DKOq17_IyChMiA_nZGbTWM5vhmX0',
    appId: '1:899155311025:web:3f4e4945f25f2be4dee590',
    messagingSenderId: '899155311025',
    projectId: 'one-vizcaya-app',
    authDomain: 'one-vizcaya-app.firebaseapp.com',
    storageBucket: 'one-vizcaya-app.firebasestorage.app',
    measurementId: 'G-RGFJYVC8DL',
  );
}
