name: one_vizcaya
description: "One Vizcaya is a cross-platform mobile application built with Flutter and Firebase, connecting the citizens of all 15 municipalities of Nueva Vizcaya to their Local Government Units (LGU)."
publish_to: 'none'
version: 1.1.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  firebase_app_check: ^0.4.1+2

  # App Packages
  url_launcher: ^6.2.6
  image_picker: ^1.0.7
  geolocator: ^14.0.2
  fluttertoast: ^9.0.0
  timeago: ^3.6.1
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  firebase_messaging: ^15.1.0
  flutter_image_compress: ^2.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.11.0
  printing: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#1565C0"
  image: assets/images/Seal_of_Nueva_Vizcaya.svg.png
  color_dark: "#0D47A1"
  image_dark: assets/images/Seal_of_Nueva_Vizcaya.svg.png
  android_12:
    image: assets/images/Seal_of_Nueva_Vizcaya.svg.png
    icon_background_color: "#1565C0"
  fullscreen: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/Seal_of_Nueva_Vizcaya.svg.png
    - assets/images/seals/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Seal_of_Nueva_Vizcaya.svg.png"